### PR TITLE
Update upstream

### PR DESCRIPTION
**Pull request by iquerejeta**
Keeping up to date our branch with upstream's stable.

### CODE REVIEW

**Comment by nankeen** [comment]
We might want to update the CI to run the vrf tests as it is not running vrf tests because autoreconf or autogen.sh -f wasn’t run in the build check. notice vrf is missing :point_down:

```
PASS: aead_aes256gcm2
PASS: aead_chacha20poly1305
PASS: aead_aes256gcm
PASS: aead_xchacha20poly1305
PASS: aead_chacha20poly13052
PASS: auth2
PASS: auth
PASS: auth3
PASS: auth6
PASS: auth5
PASS: box
PASS: auth7
PASS: box2
PASS: box7
PASS: box_easy
PASS: box_easy2
PASS: box_seal
PASS: box_seed
PASS: chacha20
PASS: codecs
PASS: core1
PASS: box8
PASS: core2
PASS: core4
PASS: core5
PASS: core6
PASS: core3
PASS: generichash
PASS: generichash2
PASS: ed25519_convert
PASS: generichash3
PASS: hash
PASS: hash3
PASS: kdf
PASS: keygen
PASS: kx
PASS: misuse
PASS: onetimeauth
PASS: onetimeauth2
PASS: onetimeauth7
PASS: metamorphic
PASS: pwhash_argon2i
PASS: randombytes
PASS: scalarmult
PASS: scalarmult2
PASS: scalarmult5
PASS: scalarmult6
PASS: scalarmult7
PASS: pwhash_argon2id
PASS: scalarmult8
PASS: secretbox
PASS: secretbox2
PASS: secretbox7
PASS: secretbox8
PASS: secretbox_easy
PASS: secretbox_easy2
PASS: secretstream
PASS: shorthash
PASS: sodium_core
PASS: sodium_utils
PASS: sodium_version
PASS: sign
PASS: stream
PASS: stream3
PASS: stream4
PASS: stream2
PASS: verify1
PASS: sodium_utils3
PASS: sodium_utils2
PASS: core_ed25519
PASS: core_ristretto255
PASS: pwhash_scrypt_ll
PASS: scalarmult_ed25519
PASS: scalarmult_ristretto255
PASS: siphashx24
PASS: xchacha20
PASS: pwhash_scrypt
============================================================================
Testsuite summary for libsodium 1.0.18
============================================================================
# TOTAL: 77
# PASS:  77
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```
Other than that the implementation matches https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-vrf-03 and no apparent changes were made between 1.0.17 and 1.0.18 on the stable branch that would seem to affect it. So it looks good to me.

**Comment by iquerejeta** [comment]
Don't manage to run the VRF tests even locally. Will look into it. Thanks for the heads up 👍

**Comment by nankeen** [comment]
Great! If it helps I managed to run it locally with:

```
./autogen.sh -f
./configure
make check
```

**Comment by iquerejeta** [comment]
it does help! Thanks 👍

**Pull request merged**
